// Realistic demo data for AfricaHome
export const defaultData = {
  users: [
    { id:'admin', type:'admin', name:'Admin AfricaHome', phone:'000000000', email:'admin@africahome.com', verified:true, joinDate:'2025-01-01' },
    { id:'u1', type:'bailleur', name:'Jean Mbarga', phone:'651810270', whatsapp:'651810270', email:'jean.mbarga@email.com', country:'Cameroun', city:'Douala', quarter:'Akwa', verified:true, joinDate:'2025-11-15', subscription:{ plan:'annual', planId:'bailleur-annual', planName:'Bailleur Annuel', price:15000, active:true, start:'2026-01-01', end:'2026-12-31' }, paymentHistory:[{ planId:'bailleur-annual', planName:'Bailleur Annuel', amount:15000, date:'2026-01-01', method:'selar' }]},
    { id:'u2', type:'bailleur', name:'Fatou Diallo', phone:'771234567', whatsapp:'771234567', email:'fatou.diallo@email.com', country:'Sénégal', city:'Dakar', quarter:'Plateau', verified:true, joinDate:'2025-12-20', subscription:{ plan:'monthly', planId:'bailleur-monthly', planName:'Bailleur Mensuel', price:2500, active:true, start:'2026-05-01', end:'2026-06-01' }, paymentHistory:[{ planId:'bailleur-monthly', planName:'Bailleur Mensuel', amount:2500, date:'2026-03-01', method:'selar' },{ planId:'bailleur-monthly', planName:'Bailleur Mensuel', amount:2500, date:'2026-04-01', method:'selar' },{ planId:'bailleur-monthly', planName:'Bailleur Mensuel', amount:2500, date:'2026-05-01', method:'selar' }]},
    { id:'u3', type:'professionnel', name:'Immobilière du Soleil', phone:'690112233', whatsapp:'690112233', email:'contact@immo-soleil.cm', country:'Cameroun', city:'Yaoundé', quarter:'Bastos', structureName:'Immobilière du Soleil SARL', niu:'P012345678', representativeName:'Marc Atangana', cniNumber:'123456789', cniPhotoUrl:'/images/apartment.png', officialDocUrl:'/images/villa.png', verified:true, verificationStatus:'approuve', verificationChecklist:{ cniPhotoLisible:true, cniNumeroValide:true, niuVerifie:true, docOfficielAuthentique:true, representantCorrespond:true, structureVerifiee:true }, verificationHistory:[ { action:'en_attente', date:'2025-10-05', by:'Système', note:'Documents soumis lors de l\'inscription' }, { action:'en_cours', date:'2025-10-06', by:'Admin AfricaHome', note:'Début de la vérification' }, { action:'approuve', date:'2025-10-07', by:'Admin AfricaHome', note:'Tous les documents validés. Compte professionnel certifié.' } ], joinDate:'2025-10-05', subscription:{ plan:'annual', planId:'pro-annual', planName:'Professionnel Annuel', price:120000, active:true, start:'2026-01-01', end:'2026-12-31' }, paymentHistory:[{ planId:'pro-annual', planName:'Professionnel Annuel', amount:120000, date:'2026-01-01', method:'selar' }]},
    { id:'u4', type:'locataire', name:'Paul Essono', phone:'655998877', email:'paul.essono@email.com', joinDate:'2026-03-10', subscription:{ plan:'one-time', planId:'locataire-access', planName:'Accès Locataire', price:1500, active:true }, accessPaid:true, paymentHistory:[{ planId:'locataire-access', planName:'Accès Locataire', amount:1500, date:'2026-03-10', method:'selar' }]},
    { id:'u5', type:'bailleur', name:'Aminata Koné', phone:'707889900', whatsapp:'707889900', email:'aminata.kone@email.com', country:'Côte d\'Ivoire', city:'Abidjan', quarter:'Cocody', verified:true, joinDate:'2026-01-18', subscription:{ plan:'annual', planId:'bailleur-annual', planName:'Bailleur Annuel', price:15000, active:true, start:'2026-02-01', end:'2027-01-31' }, paymentHistory:[{ planId:'bailleur-annual', planName:'Bailleur Annuel', amount:15000, date:'2026-02-01', method:'selar' }]},
    { id:'u6', type:'professionnel', name:'BTP Africa Construction', phone:'699445566', whatsapp:'699445566', email:'info@btpafrica.com', country:'Cameroun', city:'Douala', quarter:'Bonapriso', structureName:'BTP Africa Construction SA', niu:'M098765432', representativeName:'Jacques Fotso', cniNumber:'987654321', cniPhotoUrl:'/images/studio.png', officialDocUrl:'/images/terrain.png', verified:false, verificationStatus:'en_attente', verificationChecklist:{ cniPhotoLisible:false, cniNumeroValide:false, niuVerifie:false, docOfficielAuthentique:false, representantCorrespond:false, structureVerifiee:false }, verificationHistory:[ { action:'en_attente', date:'2025-09-01', by:'Système', note:'Documents soumis lors de l\'inscription' } ], joinDate:'2025-09-01', subscription:{ plan:'annual', planId:'pro-annual', planName:'Professionnel Annuel', price:120000, active:true, start:'2026-01-01', end:'2026-12-31' }},
    { id:'u7', type:'locataire', name:'Marie Nguema', phone:'677112233', email:'marie.nguema@email.com', joinDate:'2026-04-05', subscription:{ plan:'one-time', planId:'locataire-access', planName:'Accès Locataire', price:1500, active:true }},
    { id:'u8', type:'locataire', name:'Olivier Tchamba', phone:'698776655', email:'olivier.t@email.com', joinDate:'2026-02-14', subscription:{ plan:'one-time', planId:'locataire-access', planName:'Accès Locataire', price:1500, active:true }},
    { id:'u9', type:'bailleur', name:'Moussa Sow', phone:'775566778', whatsapp:'775566778', email:'moussa.sow@email.com', country:'Sénégal', city:'Dakar', quarter:'Mermoz', verified:false, joinDate:'2026-04-01', subscription:{ plan:'monthly', planId:'bailleur-monthly', planName:'Bailleur Mensuel', price:2500, active:true, start:'2026-05-01', end:'2026-06-01' }},
    { id:'u10', type:'locataire', name:'Aïcha Bello', phone:'656443322', email:'aicha.b@email.com', joinDate:'2026-05-01', subscription:{ plan:'one-time', planId:'locataire-access', planName:'Accès Locataire', price:1500, active:true }},
  ],
  listings: [
    { id:'l1', userId:'u1', type:'appartement', category:'location', title:'Bel Appartement 3 Pièces à Akwa', description:'Spacieux appartement de 3 pièces avec salon, cuisine équipée et 2 salles de bain. Situé dans un quartier calme et sécurisé à Akwa, proche des commerces et des transports en commun. Eau chaude 24h/24, carrelage moderne, balcon avec vue sur la ville, parking inclus.', price:85000, currency:'FCFA', country:'Cameroun', city:'Douala', quarter:'Akwa', distanceRoute:'200m', rooms:3, images:['/images/apartment.png','/images/villa.png','/images/studio.png'], available:true, createdAt:'2026-05-10', contactPhone:'651810270', contactWhatsapp:'651810270', views:247, featured:true, lat:4.0483, lng:9.7043 },
    { id:'l2', userId:'u2', type:'maison', category:'vente', title:'Villa Moderne 5 Pièces avec Jardin et Piscine', description:'Magnifique villa de 5 pièces avec grand jardin arboré, piscine privée et garage 2 voitures. Construction récente avec finitions haut de gamme : marbre au sol, cuisine italienne, dressing dans la suite parentale. Quartier résidentiel très calme. Titre foncier disponible.', price:45000000, currency:'FCFA', country:'Sénégal', city:'Dakar', quarter:'Almadies', distanceRoute:'100m', rooms:5, images:['/images/villa.png','/images/apartment.png','/images/plan3d.png'], available:true, createdAt:'2026-05-05', contactPhone:'771234567', contactWhatsapp:'771234567', views:312, featured:true, lat:14.7456, lng:-17.5139 },
    { id:'l3', userId:'u3', type:'terrain', category:'terrain', title:'Terrain Titré 500m² à Odza', description:'Terrain plat de 500m², entièrement titré et borné par un géomètre assermenté. Idéal pour construction résidentielle ou petit immeuble commercial. Accès goudronné, eau et électricité disponibles sur le site. Documents complets : titre foncier, plan de situation, certificat de propriété.', price:12000000, currency:'FCFA', country:'Cameroun', city:'Yaoundé', quarter:'Odza', distanceRoute:'50m', rooms:0, images:['/images/terrain.png','/images/villa.png'], available:true, createdAt:'2026-05-08', contactPhone:'690112233', contactWhatsapp:'690112233', views:178, lat:3.8160, lng:11.5314 },
    { id:'l4', userId:'u1', type:'studio', category:'location', title:'Studio Meublé Standing à Bonanjo', description:'Joli studio de standing entièrement meublé et équipé : lit queen, canapé, TV écran plat, climatisation, réfrigérateur, micro-ondes. Idéal pour expatrié ou jeune cadre. Eau chaude, électricité prépayée, internet fibre inclus. Gardiennage 24h/24.', price:75000, currency:'FCFA', country:'Cameroun', city:'Douala', quarter:'Bonanjo', distanceRoute:'300m', rooms:1, images:['/images/studio.png','/images/apartment.png'], available:true, createdAt:'2026-05-12', contactPhone:'651810270', contactWhatsapp:'651810270', views:403, lat:4.0245, lng:9.6926 },
    { id:'l5', userId:'u3', type:'plan3d', category:'construction', title:'Plan 3D Villa Moderne - 4 Chambres avec Terrasse', description:'Conception 3D professionnelle pour villa moderne de 4 chambres, 3 salles de bain, salon double, cuisine américaine, terrasse panoramique et espace barbecue. Livré avec plans techniques complets, devis estimatif et suivi de chantier en option.', price:250000, currency:'FCFA', country:'Cameroun', city:'Yaoundé', quarter:'Bastos', distanceRoute:'N/A', rooms:4, images:['/images/plan3d.png','/images/villa.png','/images/terrain.png'], available:true, createdAt:'2026-05-07', contactPhone:'690112233', contactWhatsapp:'690112233', views:289, featured:true },
    { id:'l6', userId:'u2', type:'chambre', category:'location', title:'Chambre Climatisée en Résidence Sécurisée', description:'Grande chambre climatisée avec salle de bain privée dans une résidence sécurisée au cœur de Mermoz. Eau chaude, WiFi, ménage hebdomadaire inclus. Cadre paisible, idéal pour célibataire ou couple sans enfants.', price:35000, currency:'FCFA', country:'Sénégal', city:'Dakar', quarter:'Mermoz', distanceRoute:'150m', rooms:1, images:['/images/apartment.png','/images/studio.png'], available:true, createdAt:'2026-05-14', contactPhone:'771234567', contactWhatsapp:'771234567', views:156 },
    { id:'l7', userId:'u5', type:'appartement', category:'location', title:'Appartement 4 Pièces Vue Lagune à Cocody', description:'Superbe appartement de 4 pièces avec vue imprenable sur la lagune Ebrié. 2 chambres climatisées, salon spacieux, cuisine aménagée, 2 salles d\'eau. Résidence avec piscine, salle de sport et gardiennage permanent.', price:250000, currency:'FCFA', country:'Côte d\'Ivoire', city:'Abidjan', quarter:'Cocody', distanceRoute:'80m', rooms:4, images:['/images/apartment.png','/images/villa.png'], available:true, createdAt:'2026-05-11', contactPhone:'707889900', contactWhatsapp:'707889900', views:198, featured:true, lat:5.3599, lng:-3.9927 },
    { id:'l8', userId:'u6', type:'maison', category:'construction', title:'Construction Clé en Main - Villa 3 Chambres', description:'Offre de construction complète pour villa 3 chambres sur votre terrain. Inclut : plans architecturaux, fondations, gros œuvre, toiture, plomberie, électricité, peinture et finitions. Garantie décennale. Délai de livraison : 8 mois. Suivi photo hebdomadaire.', price:18000000, currency:'FCFA', country:'Cameroun', city:'Douala', quarter:'Bonapriso', distanceRoute:'N/A', rooms:3, images:['/images/villa.png','/images/plan3d.png','/images/terrain.png'], available:true, createdAt:'2026-05-09', contactPhone:'699445566', contactWhatsapp:'699445566', views:134 },
    { id:'l9', userId:'u9', type:'chambre', category:'location', title:'Chambre Moderne Meublée à Ouakam', description:'Belle chambre meublée dans un appartement partagé à Ouakam. Proche de la plage et des transports. Salle de bain partagée, cuisine équipée, salon commun. Internet fibre et eau/électricité inclus dans le loyer.', price:25000, currency:'FCFA', country:'Sénégal', city:'Dakar', quarter:'Ouakam', distanceRoute:'500m', rooms:1, images:['/images/studio.png','/images/apartment.png'], available:true, createdAt:'2026-05-15', contactPhone:'775566778', contactWhatsapp:'775566778', views:87 },
    { id:'l10', userId:'u5', type:'terrain', category:'terrain', title:'Parcelle 1000m² Bord de Route à Bingerville', description:'Grande parcelle de 1000m² avec accès direct sur la route bitumée Abidjan-Bingerville. ACD (Arrêté de Concession Définitive) disponible. Zone en pleine expansion, idéal pour investissement. Eau et électricité à proximité immédiate.', price:8500000, currency:'FCFA', country:'Côte d\'Ivoire', city:'Abidjan', quarter:'Bingerville', distanceRoute:'0m', rooms:0, images:['/images/terrain.png'], available:true, createdAt:'2026-05-13', contactPhone:'707889900', contactWhatsapp:'707889900', views:145 },
  ],
  reviews: [
    { id:'r1', listingId:'l1', userId:'u4', userName:'Paul E.', rating:5, comment:'Excellent appartement ! Très propre, bien situé à Akwa. Le bailleur est très réactif et honnête. Je recommande vivement.', date:'2026-05-12' },
    { id:'r2', listingId:'l1', userId:'u7', userName:'Marie N.', rating:4, comment:'Bel espace et quartier calme. Petit bémol sur la pression d\'eau le soir, mais globalement très satisfaite de mon logement.', date:'2026-05-11' },
    { id:'r3', listingId:'l1', userId:'u8', userName:'Olivier T.', rating:5, comment:'J\'habite ici depuis 2 mois. Rien à redire, le rapport qualité-prix est imbattable à Douala.', date:'2026-05-14' },
    { id:'r4', listingId:'l2', userId:'u4', userName:'Paul E.', rating:5, comment:'Villa exceptionnelle ! Les photos reflètent parfaitement la réalité. Le jardin et la piscine sont magnifiques.', date:'2026-05-09' },
    { id:'r5', listingId:'l2', userId:'u10', userName:'Aïcha B.', rating:5, comment:'Nous avons visité cette villa en famille. C\'est un coup de cœur. La qualité des finitions est remarquable.', date:'2026-05-10' },
    { id:'r6', listingId:'l2', userId:'u7', userName:'Marie N.', rating:4, comment:'Très belle maison dans un quartier premium. Le prix est justifié par la qualité mais reste élevé.', date:'2026-05-12' },
    { id:'r7', listingId:'l3', userId:'u8', userName:'Olivier T.', rating:4, comment:'Terrain bien situé avec tous les documents en règle. Le géomètre a confirmé les limites. Sérieux.', date:'2026-05-13' },
    { id:'r8', listingId:'l3', userId:'u10', userName:'Aïcha B.', rating:5, comment:'J\'ai acheté un terrain similaire dans le même quartier. Odza est en plein essor, excellent investissement.', date:'2026-05-14' },
    { id:'r9', listingId:'l4', userId:'u7', userName:'Marie N.', rating:4, comment:'Studio très confortable et bien équipé. Le gardiennage est un vrai plus. Parfait pour un séjour professionnel.', date:'2026-05-15' },
    { id:'r10', listingId:'l4', userId:'u10', userName:'Aïcha B.', rating:5, comment:'Le meilleur studio que j\'ai trouvé à Douala. Internet rapide, eau chaude, climatisation... tout y est !', date:'2026-05-14' },
    { id:'r11', listingId:'l4', userId:'u8', userName:'Olivier T.', rating:5, comment:'Je vis ici depuis 3 mois. Le bailleur Jean est très professionnel. Studio propre et moderne.', date:'2026-05-13' },
    { id:'r12', listingId:'l5', userId:'u4', userName:'Paul E.', rating:5, comment:'Plans 3D de qualité professionnelle. L\'équipe de l\'Immobilière du Soleil a été très à l\'écoute de nos besoins.', date:'2026-05-11' },
    { id:'r13', listingId:'l5', userId:'u8', userName:'Olivier T.', rating:5, comment:'Rendu 3D impressionnant et réaliste. Les plans techniques sont très détaillés. Service recommandé.', date:'2026-05-13' },
    { id:'r14', listingId:'l6', userId:'u4', userName:'Paul E.', rating:3, comment:'Chambre correcte mais un peu petite pour le prix demandé. La résidence est sécurisée, c\'est un point positif.', date:'2026-05-16' },
    { id:'r15', listingId:'l6', userId:'u7', userName:'Marie N.', rating:4, comment:'Bon rapport qualité-prix pour Dakar. La climatisation fonctionne bien et le WiFi est stable.', date:'2026-05-15' },
    { id:'r16', listingId:'l7', userId:'u4', userName:'Paul E.', rating:5, comment:'Vue magnifique sur la lagune ! L\'appartement est spacieux et lumineux. La résidence avec piscine est un luxe.', date:'2026-05-13' },
    { id:'r17', listingId:'l7', userId:'u10', userName:'Aïcha B.', rating:4, comment:'Très bel appartement à Cocody. Le quartier est calme et bien desservi. Seul bémol : les charges sont élevées.', date:'2026-05-14' },
    { id:'r18', listingId:'l8', userId:'u7', userName:'Marie N.', rating:5, comment:'BTP Africa a construit la maison de mes parents. Travail sérieux, respect des délais. Très satisfaite.', date:'2026-05-12' },
    { id:'r19', listingId:'l8', userId:'u8', userName:'Olivier T.', rating:4, comment:'Devis détaillé et transparent. Le suivi photo est un vrai plus pour suivre l\'avancement du chantier.', date:'2026-05-14' },
    { id:'r20', listingId:'l9', userId:'u10', userName:'Aïcha B.', rating:3, comment:'Chambre propre mais la colocation n\'est pas pour tout le monde. L\'emplacement à Ouakam est top.', date:'2026-05-16' },
    { id:'r21', listingId:'l10', userId:'u8', userName:'Olivier T.', rating:5, comment:'Excellent investissement ! La zone de Bingerville se développe rapidement. Documents en règle.', date:'2026-05-15' },
    { id:'r22', listingId:'l10', userId:'u4', userName:'Paul E.', rating:4, comment:'Grande parcelle bien placée. Le prix est raisonnable vu l\'emplacement en bord de route.', date:'2026-05-14' },
  ],
  favorites: ['l2','l4','l7'],
  notifications: [],
  currentUser: null
};

// Generate notifications per user
export function getNotificationsForUser(user, listings) {
  if (!user) return [];
  const now = new Date();
  const base = [
    { id:'n0', text:'🎉 Bienvenue sur AfricaHome ! Explorez les annonces disponibles.', time:'Lors de l\'inscription', read:true, date: user.joinDate },
  ];
  if (user.type === 'locataire') {
    return [...base,
      { id:'n1', text:'🏠 Nouvelle annonce à Douala : Appartement 3P à Akwa — 85 000 FCFA/mois', time:'Il y a 2h', read:false },
      { id:'n2', text:'🔥 Annonce populaire : Studio Meublé à Bonanjo — déjà 403 vues !', time:'Il y a 5h', read:false },
      { id:'n3', text:'🆕 3 nouvelles annonces correspondent à vos critères de recherche', time:'Il y a 1j', read:false },
      { id:'n4', text:'💡 Astuce : ajoutez des annonces en favoris pour les retrouver facilement', time:'Il y a 2j', read:true },
      { id:'n5', text:'⭐ Votre avis compte ! Notez les logements que vous avez visités', time:'Il y a 3j', read:true },
    ];
  } else if (user.type === 'bailleur') {
    const myListings = listings.filter(l => l.userId === user.id);
    const totalViews = myListings.reduce((s,l) => s+(l.views||0), 0);
    return [...base,
      { id:'n1', text:`👁 Vos annonces ont atteint ${totalViews} vues au total !`, time:'Il y a 1h', read:false },
      { id:'n2', text:'⭐ Nouveau avis sur votre annonce « '+( myListings[0]?.title || 'Annonce') +' »', time:'Il y a 3h', read:false },
      { id:'n3', text:'📊 Rapport hebdomadaire : vos annonces performent bien cette semaine', time:'Il y a 1j', read:false },
      { id:'n4', text:'💳 Rappel : votre abonnement expire le '+(user.subscription?.end||'bientôt'), time:'Il y a 2j', read:true },
      { id:'n5', text:'📸 Conseil : ajoutez plus de photos pour augmenter vos vues de 40%', time:'Il y a 4j', read:true },
    ];
  } else { // professionnel
    const myListings = listings.filter(l => l.userId === user.id);
    return [...base,
      { id:'n1', text:'🏆 Votre structure est maintenant vérifiée ✅ — plus de visibilité !', time:'Il y a 2h', read:false },
      { id:'n2', text:`📈 ${myListings.length} annonces actives · Performance en hausse de 15%`, time:'Il y a 6h', read:false },
      { id:'n3', text:'⭐ 2 nouveaux avis reçus cette semaine sur vos annonces', time:'Il y a 1j', read:false },
      { id:'n4', text:'🔔 Un locataire a ajouté votre annonce en favoris', time:'Il y a 1j', read:true },
      { id:'n5', text:'💼 Abonnement Pro actif jusqu\'au '+(user.subscription?.end||'bientôt'), time:'Il y a 3j', read:true },
    ];
  }
}
